[env]
PKG_CONFIG = { value = "tools/native-media/pkg-config.sh", relative = true }
PKG_CONFIG_ALLOW_CROSS = "1"
RLOTTIE_STATIC = "1"
LIBWEBP_STATIC = "1"
LIBWEBPDEMUX_STATIC = "1"
LIBWEBPMUX_STATIC = "1"
LIBAVUTIL_STATIC = "1"
LIBAVCODEC_STATIC = "1"
LIBAVFORMAT_STATIC = "1"
LIBSWSCALE_STATIC = "1"
