[package]
name = "memedock-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
memedock-domain = { path = "../domain" }
memedock-storage = { path = "../storage" }
tokio = { workspace = true, features = ["macros"] }
uuid.workspace = true
image.workspace = true
zip.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
reqwest.workspace = true
webpki-root-certs.workspace = true
flate2.workspace = true
rlottie.workspace = true
ffmpeg-next.workspace = true

[dev-dependencies]
tempfile.workspace = true
webp-animation.workspace = true

[lints]
workspace = true
